# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 网站标题
title: 半度微凉
# 网站副标题
subtitle: Taoweidong
# 网站描述
description: 我的个人博客系统
# 网站的关键词。使用半角逗号 , 分隔多个关键词。
keywords: Java,技术,SpringCloud,Nginx,GitLab,Linux,微服务
author: 半度微凉
# 网站使用的语言
language: zh-Hans
# 网站时区
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'

#url 	网址
url: http://www.taoweidong.com
#root 	网站根目录
root: /
#permalink 	文章的 永久链接 格式 	:year/:month/:day/:title/
permalink: :year/:month/:day/:title/
#permalink_defaults 	永久链接中各部分的默认值
permalink_defaults:

# 目录
#source_dir 	资源文件夹，这个文件夹用来存放内容。
source_dir: source
#public_dir 	公共文件夹，这个文件夹用于存放生成的站点文件
public_dir: public
#tag_dir 	标签文件夹
tag_dir: tags
#archive_dir 	归档文件夹
archive_dir: archives
#category_dir 	分类文件夹
category_dir: categories
#code_dir 	Include code 文件夹
code_dir: downloads/code
#i18n_dir 	国际化（i18n）文件夹
i18n_dir: :lang
#skip_render 	跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。

#设置不被渲染的文件
# 路径是相对source目录的
# 不对google7caf449f9ab0f94b.html与your-other-ignore-file进行渲染，保持文件原有内容
skip_render:
  - "README.md"
#skip_render:
#  - 'baidu.html'
#  - 'google.html'

# Writing
#new_post_name 	新文章的文件名称
new_post_name: :title.md # File name of new posts
#default_layout 	预设布局
default_layout: post
#auto_spacing 	在中文和英文之间加入空格
#titlecase 	把标题转换为 title case
titlecase: false # Transform title into titlecase
#external_link 	在新标签中打开链接
external_link: true # Open external links in new tab
#filename_case 	把文件名称转换为 (1) 小写或 (2) 大写
filename_case: 0
#render_drafts 	显示草稿
render_drafts: false
#post_asset_folder 	启动 Asset 文件夹
post_asset_folder: false
#relative_link 	把链接改为与根目录的相对位址
relative_link: false
#future 	显示未来的文章
future: true
#highlight 	代码块的设置
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 5
  order_by: -date

# Category & Tag
#default_category 	默认分类
default_category: uncategorized
#category_map 	分类别名
category_map:
#tag_map 	标签别名
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
# per_page 	每页显示的文章量 (0 = 关闭分页功能)
per_page: 10
# pagination_dir 	分页目录
pagination_dir: page

# 插件配置 Extensions
plugins:
  hexo-generator-feed
#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

## Themes: https://hexo.io/themes/
## landscape
#theme 	当前主题名称。值为false时禁用主题
theme: yilia-plus

##你的头像url
avatar: http://img3.imgtn.bdimg.com/it/u=1121475478,2545730346&fm=214&gp=0.jpg

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

# Deployment  deploy 	部署部分的设置
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git 
  repo: ssh://git@github.com/taoweidong/taoweidong.github.io.git
  branch: master
  message: "博客更新: {{ now('YYYY-MM-DD HH:mm:ss') }}"
